version: '3.4'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: laravel
    restart: unless-stopped
    networks:
      - laravel
    
  mysql:
    image: mysql/mysql-server:5.6
    container_name: laravel-mysql
    restart: unless-stopped
    networks:
      - laravel
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"

  nginx:
    build: ./nginx
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - laravel
    networks:
      - laravel
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/project.conf:/etc/nginx/conf.d/project.conf
      
networks:
  laravel:
    external:
      name: laravel
