version: "3.9"

services:
    backend:
        build: "./laravel/"
        volumes:
            - "laravel:./../"
        network: laravel
        links: 
            - "mysql"
            - "nginx"

    nginx:
        build: "./nginx/"


    mysql:
        image: mysql
        container_name: laravel-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
        - 33062:3306
        environment:
        MYSQL_ROOT_HOST: "%"
        MYSQL_ROOT_PASSWORD: "root"