version: '3.4'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: laravel-php
    networks:
      - laravel
    #Use volumes to link the laravel project outside the docker container
    volumes:
      - project-volume:/var/www/laravel/laravel-project/
    
  mysql:
    image: mysql/mysql-server:5.6
    container_name: laravel-mysql
    networks:
      - laravel
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"

  nginx:
    build: ./nginx
    container_name: laravel-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - laravel
    networks:
      - laravel
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/laravel.local.conf
      
volumes:
   project-volume:

networks:
  laravel:
    external:
      name: laravel
