version: '3.4'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: project:laravel
    restart: always
    depends_on:
      - mysql
      - redis
    container_name: laravel-php
    networks:
      - laravel
    #Use volumes to link the laravel project outside the docker container
    volumes:
      - ${PWD}/rebuild-db.sh:/var/www/laravel/rebuild-db.sh
      - project:/var/www/laravel/laravel-project/
    
  mysql:
    image: mysql/mysql-server:8.0
    container_name: laravel-mysql
    #Only needed with mysql 8 till connector updates to use caching_sha2_password
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - laravel
    ports:
      - 33069:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"

  nginx:
    build: ./nginx
    image: project:nginx
    container_name: laravel-nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - laravel
    networks:
      - laravel
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/laravel.local.conf
      - project-assets:/var/www/assets

  redis:
    image: redis:latest
    container_name: laravel-redis
    restart: always
    ports:
      - 63790:6379
    networks:
      - laravel

volumes:
  project:
    driver_opts:
      type: none
      #device: path to your project
      o: bind

  project-assets:
    driver_opts:
      type: none
      #device: path to public folder for static files (css, js)
      o: bind

networks:
  laravel:
    external:
      name: laravel